cluster:
    address: submit.aci.ics.psu.edu
    username: ktt5121
    key: 0 #provide key path to avoid entering password

build:
    local: 
        folder: build
        template: 
            name: build.template #Must have .template extension
            overwrite: True
    remote:
        workplace_folder: Github
        project_folder: PSU-CIDD-Malaria-Simulation-Test
    repo:
        url: https://github.com/KienTTran/PSU-CIDD-Malaria-Simulation.git
        branch: dev
    
run:
    local:
        folder: run
        generate_config_files: 
            script: generate_configs.py
            config_folder: generated_inputs
            parameters:
             - parameters.yml #parameters to generate configs
             - input.yml #Input template for exe file
             - job_template.template #Must have .template after file name
             - submit_all_jobs.template #Must have .template after file name
    remote:
        workplace_folder: work #On cluster
        project_folder:
            name: Pipeline_1
            bin: bin
            output: output
            raw: raw
        exe: MaSim
    
    
    
