ssh:
    address: submit.aci.ics.psu.edu
    username: &username_anchor ktt5121
    key: 0 #provide key path to avoid entering password

build:
    remote:
        workplace_folder: Github
        project_folder: PSU-CIDD-Malaria-Simulation-Test
    repo:
        url: https://github.com/KienTTran/PSU-CIDD-Malaria-Simulation.git
        branch: dev
    script:
        name: build.sh #This file name will be set to be output of generator as well
        parameters:
    generator:
        script: generate_build_scripts.py
        folder: build
        parameters:
         - build.template
         - *username_anchor
             
upload:
    remote:
        workplace_folder: work
        project_folder: 
            name: &project_name_anchor Pipeline_1
            bin: bin
            output: output
            raw: raw
    files:
     - configs.csv
     - job_template.pbs
     - submit_all_jobs.pbs
     - generated_configs.tar.gz
    generator:
        script: generate_upload_files.py
        folder: upload
        parameters:
         - generated_configs
         - parameters.yml #parameters to generate configs
         - input.yml
         - *username_anchor
         - *project_name_anchor
         - job_template.template
         - submit_all_jobs.template
 
 run:
    remote:
        build_folder: 
        workplace_folder: work
         
    
    
    
