ssh:
    address: submit.aci.ics.psu.edu
    username: &username ktt5121

project:
    folder: Github2/PSU-CIDD-Malaria-Simulation-Test2
    exe: build/bin/MaSim
    repo:
        url: https://github.com/KienTTran/PSU-CIDD-Malaria-Simulation.git
        branch: dev
         
upload:
    files:
    - work/Pipeline_1/output
    - work/Pipeline_1/raw
    - work/Pipeline_1/bin:
        - https://raw.githubusercontent.com/KienTTran/PSU-CIDD-Malaria-Simulation-Scripts/master/python/Pipeline/Kubeflow/Masim/upload/generate_configs.py
        - https://raw.githubusercontent.com/KienTTran/PSU-CIDD-Malaria-Simulation-Scripts/master/python/Pipeline/Kubeflow/Masim/upload/parameters.yml
        - https://raw.githubusercontent.com/KienTTran/PSU-CIDD-Malaria-Simulation-Scripts/master/python/Pipeline/Kubeflow/Masim/upload/input.yml
        - https://raw.githubusercontent.com/KienTTran/PSU-CIDD-Malaria-Simulation-Scripts/master/python/Pipeline/Kubeflow/Masim/upload/job_template.template
        - https://raw.githubusercontent.com/KienTTran/PSU-CIDD-Malaria-Simulation-Scripts/master/python/Pipeline/Kubeflow/Masim/upload/submit_all_jobs.template
    - work/Pipeline_1/build:
        - https://raw.githubusercontent.com/KienTTran/PSU-CIDD-Malaria-Simulation-Scripts/master/python/Pipeline/Kubeflow/Masim/build/generate_build_script.py
        - https://raw.githubusercontent.com/KienTTran/PSU-CIDD-Malaria-Simulation-Scripts/master/python/Pipeline/Kubeflow/Masim/build/build.template
        
generator:
    build:
        script: generate_build_script.py
        parameters:
        - build.template
        - *username
        - build.sh
    config:
        script: generate_configs.py
        parameters:
        - generated_configs
        - parameters.yml
        - input.yml
        - *username
        - Pipeline_1
        - job_template.template
        - submit_all_jobs.template
    
        
        
        
     
    
                