ssh:
    address: submit.aci.ics.psu.edu
    username: &username ktt5121
    key: 0 #provide key path to avoid entering password

project:
    folder: Github2/PSU-CIDD-Malaria-Simulation-Test2
    exe: build/bin/MaSim
        
build:
    repo:
        url: https://github.com/KienTTran/PSU-CIDD-Malaria-Simulation.git
        branch: dev
             
upload:
    local: upload
    remote:
        files:
        - work/Pipeline_1/output
        - work/Pipeline_1/bin:
            - configs.csv
            - generated_configs.tar.gz
        - work/Pipeline_1/raw:
            - job_template.pbs
            - submit_all_jobs.pbs
    generator:
        name: generate_upload_files.py
        folder: upload
        parameters:
        - generated_configs
        - parameters.yml
        - input.yml
        - *username
        - Pipeline_1
        - job_template.template
        - submit_all_jobs.template
        
schedule:
    folder: work/Pipeline_1
    bin: bin/MaSim
    pbs: raw/submit_all_jobs.pbs
        
        
        
     
    
                