ssh:
    address: submit.aci.ics.psu.edu
    username: &username ktt5121

project:
    folder: Github2/PSU-CIDD-Malaria-Simulation-Test2
    exe: build/bin/MaSim
        
build:
    repo:
        url: https://github.com/KienTTran/PSU-CIDD-Malaria-Simulation.git
        branch: dev
         
upload:
    files:
    - work/Pipeline_1/output
    - work/Pipeline_1/raw
    - work/Pipeline_1/bin:
        - generate_configs.py
        - parameters.yml
        - input.yml
        - job_template.template
        - submit_all_jobs.template
    generator:
        script: generate_configs.py
        parameters:
        - generated_configs
        - parameters.yml
        - input.yml
        - *username
        - Pipeline_1
        - job_template.template
        - submit_all_jobs.template
        
schedule:
    folder: work/Pipeline_1
    bin: bin/MaSim
    pbs: raw/submit_all_jobs.pbs
        
        
        
     
    
                