#!/bin/bash
#PBS -A mfb9_b_g_sc_default
#PBS -N submit_jobs
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=96:00:00

# Get started
cd $PBS_O_WORKDIR
sleep 10

TARGET=3900
SLEEP=300
USER_NAME=ktt5121

# Count the current jobs, pending or running
get_job_count(){
  # The grep is to remove the header, there may be a better way.
  qstat -u $USER_NAME | grep $USER_NAME | wc -l
}

# Global job counter
COUNTER=$(get_job_count)

FROM=0
TO=399

for NUMBERS in `seq $FROM $TO`; do
	# Wait until the number of job is under the limit, then submit.
	while [ $COUNTER -ge $TARGET ]; do
		sleep $SLEEP
		COUNTER=$(get_job_count)
	done
	qsub -v NUMBER_ARG=$NUMBERS,INPUT_FILE=$NUMBERS.yml job_template.pbs
	let "COUNTER++"
done

