#!/bin/bash
#PBS -A mfb9_b_g_sc_default
#PBS -N submit_jobs
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=96:00:00

# Get started
cd $PBS_O_WORKDIR
sleep 10

TARGET=3900
SLEEP=300
USER_NAME=ktt5121

# Count the current jobs, pending or running
get_job_count(){
  # The grep is to remove the header, there may be a better way.
  qstat -u $USER_NAME | grep $USER_NAME | wc -l
}

# Global job counter
COUNTER=$(get_job_count)

FROM=0
TO=143
REP=10

for i in `seq $FROM $TO`;do

	N_FROM=$((i*1000))
	N_TO=$((i*1000 + REP-1))
	
	for NUMBERS in `seq $N_FROM $N_TO`; do
		echo "$NUMBERS - $i.yml"
	
		# Wait until the number of job is under the limit, then submit.
		while [ $COUNTER -ge $TARGET ]; do
			sleep $SLEEP
			COUNTER=$(get_job_count)
		done
		qsub -v NUMBER_ARG=$NUMBERS,INPUT_FILE=$i.yml job_template.pbs
		let "COUNTER++"
	done
done
