#!/bin/bash

#PBS -l nodes=1:ppn=1

#PBS -l walltime=168:00:00

#PBS -l pmem=128gb

#PBS -A mfb9_b_g_sc_default

#PBS -j oe

#PBS -o $HOME/Simulations/Results/#TAG#/log/

#PBS -e $HOME/Simulations/Results/#TAG#/log/

# Get started

echo "Job started on $(hostname) at $(date)"

# Go to the correct place

cd $PBS_O_WORKDIR

# Run the job itself

# Arguments from Schedule_Run_*.sh
# qsub -F ${binName} ${tag} ${i}
# $1 - ${binName}
# $2 - ${tag}
# $3 - ${i}
cd $HOME/Simulations/bin

./MaSim_${1} -i $HOME/Simulations/Results/${2}/config/sim_prmc_${2}_${3}.yml -r MonthlyReporter -o "$HOME/Simulations/Results/${2}/output/" -j ${3}

# Finish up

echo "Job Ended at $(date)"
