#IMPORTANT1: 
#To be generated as input parameters, either use (start,stop,step/total) or [value1,value2,...].
#In example below, population, start_year, end_year, replicate parameters will not be generated in inputs.csv file

#IMPORTANT2:
#The turple (value1,value2,value3) will accept the value3 as total_output (if value > 1) or step (if value <= 1.0)
#and value1 as start and value2 as stop
#If total_output is supplied, the step will be calculated using step = (start-stop)/total_output
#start, stop and step will be supplied to np.arange() to generate value array for each parameter
#Ex1: (0,1,4) will generate [0.0,0.25,0.5,0.75]
#Ex2: (0,1,0.25) will generate [0.0,0.25,0.5,0.75]

population: 100000
beta: (0.05,4.01,20)
z: (1,10.01,0.2)
kappa: (0.1,2.51,0.1)
prmc_size: [120]
ifr: [0.0,0.19]
treatment: [0.0,0.5]
start_year: 2000
end_year: 2012
replicate: 1

# # Test
# population: 100000
# beta: [0.05,0.1]
# z: [1,2]
# kappa: [0.1,0.2]
# prmc_size: [120]
# ifr: [0.0,0.19]
# treatment: [0.0,0.5]
# start_year: 2000
# end_year: 2012
# replicate: 1