binary: ["Dev_Roulette"]
location: [1]
population: [500000]
beta: [0.05,0.056,0.26]
therapy_id: [0]
prmc_size: [20,40,80,160]
ifr: [0.0, 0.04, 0.08, 0.12, 0.16, 0.20]
start_year: [2000]
end_year: [2030]
replicates: [10]