#!/bin/bash
#PBS -A mfb9_b_g_sc_default
#PBS -N submit_jobs
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=96:00:00

# Get started
cd $PBS_O_WORKDIR
sleep 10

TARGET=3900
SLEEP=300
USER_NAME=ktt5121

# Count the current jobs, pending or running
get_job_count(){
  # The grep is to remove the header, there may be a better way.
  qstat -u $USER_NAME | grep $USER_NAME | wc -l
}

input_files=(
"sim_prmc_pop_500000_beta_0.050_ifr_0.000_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.040_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.080_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.120_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.160_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.200_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.000_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.040_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.080_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.120_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.160_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.200_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.000_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.040_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.080_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.120_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.160_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.200_prmc_size_20.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.000_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.040_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.080_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.120_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.160_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.200_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.000_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.040_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.080_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.120_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.160_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.200_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.000_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.040_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.080_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.120_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.160_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.200_prmc_size_40.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.000_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.040_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.080_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.120_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.160_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.200_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.000_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.040_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.080_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.120_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.160_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.200_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.000_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.040_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.080_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.120_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.160_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.200_prmc_size_80.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.000_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.040_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.080_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.120_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.160_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.050_ifr_0.200_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.000_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.040_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.080_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.120_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.160_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.056_ifr_0.200_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.000_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.040_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.080_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.120_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.160_prmc_size_160.yml",
"sim_prmc_pop_500000_beta_0.260_ifr_0.200_prmc_size_160.yml"
)

# Global job counter
COUNTER=$(get_job_count)

FROM=0
TO=9

for i in "${!input_files[@]}";do
        echo ${input_files[${i}]}
        for NUMBERS in `seq $FROM $TO`; do
		echo "$NUMBERS - ${input_files[${i}]}"
		
		# Wait until the number of job is under the limit, then submit.
		while [ $COUNTER -ge $TARGET ]; do
			sleep $SLEEP
			COUNTER=$(get_job_count)
		done
                qsub -v NUMBER_ARG=$NUMBERS,INPUT_FILE=${input_files[${i}]} job_template.pbs
		let "COUNTER++"
        done
        FROM=$((FROM + 1000))
        TO=$((TO + 1000))
done

