binary: ["Dev_Roulette"]
location: [1]
population: [1000000]
beta: [0.1, 0.3, 0.5, 0.7]
therapy_id: [0]
prmc_size: [800]
ifr: [0.0, 0.4, 0.8, 0.12, 0.16, 0.20]
start_year: [2000]
end_year: [2020]
replicates: [10]